### ISSUE TITLE
Using multiple image folders

### ISSUE THREAD

**Issue by siwhitehouse** [ozibozkurt/mental-health-project#11]
There are three folders containing images:

- [img-joanna](https://github.com/ozibozkurt/mental-health-project/tree/main/img-joanna)
- [img-nage](https://github.com/ozibozkurt/mental-health-project/tree/main/img-nage)
- [img](https://github.com/ozibozkurt/mental-health-project/tree/main/img)

I think that this is poor practice and that all of the images should be inside a single folder. There may be subfolders beneath that. 

@Nagehan1 @joannajurczuk94

**Comment by Mesgna616** [comment]
Thank you Simon, we have sorted out the folder issues as per your advice.

**Comment by ozibozkurt** [comment]
Hi Simon, we fixed the issues and we added all the pictures to the main img folder.

**Comment by ozibozkurt** [comment]
Hi @siwhitehouse, hopefully, you are well, I think we fixed the issues, Could you check the problems if everything is ok I will close the issues.

**Comment by siwhitehouse** [comment]
@Mesgna616 @ozibozkurt 

Thank you. I am happy to close this issue now.
